export const DISMISS_ERROR =  'DISMISS_ERROR';
export const SET_FETCHING_USER_STATE =  'SET_FETCHING_USER_STATE';
export const FETCH_USER_SUCCESSFULLY =  'FETCH_USER_SUCCESSFULLY';
export const SET_ERROR_MESSAGE =  'SET_ERROR_MESSAGE';
export const SET_FETCHING_REPOS_STATE =  'SET_FETCHING_REPOS_STATE';
export const FETCH_REPOS_SUCCESSFULLY =  'FETCH_REPOS_SUCCESSFULLY';
export const SET_SELECTED_REPO =  'SET_SELECTED_REPO';